# Generated by Django 4.2.7 on 2024-01-30 09:04

import apps.tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=245)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=apps.tasks.models.one_week_hence)),
            ],
        ),
    ]
