version: '3.9'


services:
  pgdb:
    image: "postgres:14.3"
    container_name: pgdb
    env_file:
      - env/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    container_name: api
    env_file:
      - env/.env.dev
    volumes:
      - ./:/opt/app
    depends_on:
      - pgdb
    entrypoint: ""
    command: /home/todo-api/docker-entrypoint-dev.sh
    ports:
      - "8000:8000"

  celery:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-celery
    container_name: "api_celery"
    env_file:
      - env/.env.dev
    volumes:
      - ./:/opt/app
    depends_on:
      - pgdb
      - api

  redis:
    image: redis:7.0.11-alpine

volumes:
  db_data:
