FROM python:3.11.5-slim-bullseye
ENV PIP_DISABLE_PIP_VERSION_CHECK true
ENV PYTHONDONTWRITEBYTECODE true
ENV PYTHONUNBUFFERED true
WORKDIR /code
COPY ./requirements.txt .
RUN pip install -r requirements.txt
COPY . .
CMD ["celery", "-A", "core", "worker", "--loglevel=INFO", "--beat", "--scheduler","django_celery_beat.schedulers:DatabaseScheduler", "-l", "info"]
