FROM python:3.11

ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY ../requirements.txt /opt/app/

RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir

COPY .. /opt/app/

RUN useradd -ms /bin/bash todo-api
RUN chown -R todo-api:todo-api /opt/app

ADD scripts/docker-entrypoint-dev.sh /home/todo-api/docker-entrypoint-dev.sh
ADD scripts/check_service.py /home/todo-api/check_service.py

RUN chmod +x /home/todo-api/docker-entrypoint-dev.sh
USER todo-api

ENTRYPOINT ["/home/todo-api/docker-entrypoint-dev.sh"]
